"use strict";
exports.__esModule = true;
var user_1 = require("./user");
exports.user = user_1["default"];
var book_1 = require("./book");
exports.book = book_1["default"];
var general_1 = require("./general");
exports.general = general_1["default"];
var service_1 = require("./service");
exports.service = service_1["default"];
